### PR TITLE
fix(adjust): added missing AdjustConfig method

### PR DESCRIPTION
**Pull request by uerceg**
- Added missing `hasConversionValueUpdatedCallbackListener()` method to `AdjustConfig` to fix https://github.com/adjust/cordova_sdk/issues/147.

### CODE REVIEW

**Comment by uerceg** [comment]
👋 @danielsogl Just a friendly reminder ping. 🍺

**Comment by FatManiac** [comment]
@danielsogl Sorry to bother you but when a new release including those changes will be available ?

**Comment by FatManiac** [comment]
@danielsogl sorry to ping you again but it's very important for us, any news ?

**Comment by danielsogl** [comment]
@FatManiac sorry I was bussy the last two weeks. A new patch version should be available

**Pull request merged**
