### PR TITLE
Added missing android bluetooth permissions

### PR DESCRIPTION
**Pull request by alam94h**
I just added a few missing android permissions related with bluetooth on android api level 31, I have already tried downloading this library and adding them on my local without any problem so, hopefully, this won't create any new bugs.

### CODE REVIEW

**Comment by exsjabe** [comment]
Bump

**Comment by exsjabe** [comment]
> Bump

To be more verbose, I implemented this change locally as well and it solved all my issues with the new Android 12 permissions. I would really prefer if this PR was accepted.

**Comment by NeilCresswell** [comment]
Noticed BLUETOOTH_ADVERTISE is also missing in this PR, which is present in the underlying Cordova plugin, so have included the two permissions added in this PR plus BLUETOOTH_ADVERTISE, and some new permissions for Android 13 here:
https://github.com/danielsogl/awesome-cordova-plugins/pull/4295

**Comment by alam94h** [comment]
Thanks for the up @exsjabe 

@NeilCresswell thank you, our team is also getting ready for Android 13, so this is quite helpful. 

Closing this PR, any one looking for those changes should go straight to the PR #4295

**Pull request closed without merging**
