### PR TITLE
feat(clevertap): support new clevertap changes 

### PR DESCRIPTION
**Pull request by piyush-kukadiya**
- Adds public methods for suspending, discarding & resuming InApp Notifications
- Adds public methods to increment/decrement values set via User properties
- Deprecates `profileGetCleverTapID()` and `profileGetCleverTapAttributionIdentifier()` methods
- Adds a new public method `getCleverTapID()` as an alternative to above deprecated methods
- Supports [CleverTap iOS SDK v3.10.0](https://github.com/CleverTap/clevertap-ios-sdk/releases/tag/3.10.0)
- Supports [CleverTap Android SDK v4.2.0](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/core-v4.2.0)

### CODE REVIEW

**Comment by darshanclevertap** [comment]
@danielsogl We have added some new methods to the CleverTap Cordova Plugin and need support for it in Ionic as well. If possible, could you please expedite the merge process since we have a few clients waiting to use this?

**Review by danielsogl — APPROVED** [review]

**Comment by piyush-kukadiya** [comment]
@danielsogl Thanks for merge. When is the next release scheduled to take off?

**Comment by danielsogl** [comment]
@piyush-kukadiya I will create a release later today :)

**Comment by piyush-kukadiya** [comment]
@danielsogl Thanks a ton.

**Pull request merged**
